artifact_uri: file:D:/Projects/creditcard-fraud-detection/notebooks/../mlruns_mn/148532240752397568/0a094744d9ee41a9be3f6ee6ff1efb76/artifacts
end_time: 1776279574771
entry_point_name: ''
experiment_id: '148532240752397568'
lifecycle_stage: active
run_id: 0a094744d9ee41a9be3f6ee6ff1efb76
run_name: resilient-worm-795
source_name: ''
source_type: 4
source_version: ''
start_time: 1776279572194
status: 3
tags: []
user_id: matth
